name: Flass CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Install and Test
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{matrix.python-version}}
      uses: actions/setup-python@v2
      with:
        python-version: ${{matrix.python-version}}
    - name: Install package
      run: |
        pip --version
        pip install --upgrade pip
        pip install .
    - name: Check formatting
      run: |
        pip install black
        black flass tests
    - name: Run tests
      run: |
        pip install pytest
        pytest tests/
