name: Flass PyPI

on:
  release:
    types: [published]

jobs:
  publish-to-pypi:
    name: build-push
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{matrix.python-version}}
      uses: actions/setup-python@v2
      with:
        python-version: ${{matrix.python-version}}
    - name: Build
      run: |
        python setup.py sdist
        python setup.py bdist_wheel
    - name: Publish
      env:
        TWINE_PASSWORD: ${{ secrets.PYPI }}
      run: |
        pip install twine
        twine upload -u __token__ --skip-existing dist/*
