name: Flass PyPI

on:
  release:
  push:
    tags:
      - "*"

jobs:
  publish-to-pypi:
    name: build-push
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{matrix.python-version}}
      uses: actions/setup-python@v2
      with:
        python-version: ${{matrix.python-version}}
    - name: Build
        run: |
          python setup.py sdist bdist_wheel
    - name: Publish
      env:
        PYPI_TOKEN: ${{ secrets.PYPI }}
      run: |
        pip install twine
        twine upload -u kminaister --skip-existing dist/*
